# Курс Фреймворк PyTorch для разработки искусственных нейронных сетей

# Практическое задание урока 1. Введение в PyTorch

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).type(torch.float32)
print("x :\n%s\n" % x)

x :
tensor([[[-0.9636,  0.7609,  0.2220, -1.1732, -0.9533],
         [ 0.8485,  0.3369,  1.4835, -0.7108,  0.8345],
         [ 0.3785, -1.5172, -2.0121, -2.0604, -1.1774],
         [ 1.2347,  1.1043, -0.0478,  0.4468, -0.4029]],

        [[-0.2676, -1.4492,  0.1982, -0.4225,  1.1525],
         [ 0.4042,  0.6213,  0.5164, -0.2193,  1.3373],
         [-0.2184,  0.1457,  0.1730, -0.9411, -0.0611],
         [ 1.4689, -1.4441, -0.4151, -0.3592,  1.0585]],

        [[-0.6451, -0.5762, -0.1824,  0.0364,  1.3505],
         [-0.1497,  0.5495, -1.0902, -0.0910, -1.2871],
         [ 0.4673,  0.6946, -0.1390,  0.8559, -1.1570],
         [-0.3609, -2.9571,  0.9831, -1.8477,  1.5036]]])



In [4]:
# Выведите его форму (shape)

print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [5]:
# Приведите его к форме 6 X 10

x.resize_(6, 10)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([6, 10])



In [162]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [6]:
x.resize_(3, 4, 5)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [7]:
vec = torch.FloatTensor([1, 4, 2, 2, 1])

In [8]:
x * vec

tensor([[[ -0.9636,   3.0434,   0.4440,  -2.3463,  -0.9533],
         [  0.8485,   1.3475,   2.9669,  -1.4216,   0.8345],
         [  0.3785,  -6.0689,  -4.0243,  -4.1209,  -1.1774],
         [  1.2347,   4.4172,  -0.0956,   0.8936,  -0.4029]],

        [[ -0.2676,  -5.7968,   0.3963,  -0.8451,   1.1525],
         [  0.4042,   2.4850,   1.0327,  -0.4386,   1.3373],
         [ -0.2184,   0.5826,   0.3460,  -1.8822,  -0.0611],
         [  1.4689,  -5.7765,  -0.8303,  -0.7185,   1.0585]],

        [[ -0.6451,  -2.3048,  -0.3648,   0.0729,   1.3505],
         [ -0.1497,   2.1981,  -2.1804,  -0.1820,  -1.2871],
         [  0.4673,   2.7783,  -0.2780,   1.7117,  -1.1570],
         [ -0.3609, -11.8284,   1.9661,  -3.6954,   1.5036]]])

In [9]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [10]:
x.resize_(6, 10)
torch.matmul(x, x.transpose(0,1)).size()

torch.Size([6, 6])

In [11]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [12]:
from torch.autograd import Variable

In [13]:
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
z = Variable(torch.ones(3), requires_grad = True)
t = Variable(torch.ones(3), requires_grad = True)

In [15]:
y = x**3 + z - 75*t
print(y)

tensor([-73.0000, -73.8750, -66.0000], grad_fn=<SubBackward0>)


In [16]:
y.backward(torch.ones(3))

In [17]:
print("Производная в точке x = (1, 0.5, 2) : %s\n" % (x.grad))

Производная в точке x = (1, 0.5, 2) : tensor([ 3.0000,  0.7500, 12.0000])



In [18]:
# Создайте единичный тензор размера 5x6

x = torch.ones(5,6)
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

X размеры : torch.Size([5, 6])

X тип : <class 'torch.Tensor'>



In [19]:
# Переведите его в формат numpy

x = x.numpy()
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

X размеры : (5, 6)

X тип : <class 'numpy.ndarray'>

